/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LabReportsRouteImport } from './routes/lab-reports'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReportsRoute = LabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/inquiries': typeof InquiriesRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lab-reports': typeof LabReportsRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/inquiries': typeof InquiriesRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lab-reports': typeof LabReportsRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/inquiries': typeof InquiriesRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lab-reports': typeof LabReportsRoute
  '/messages': typeof MessagesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/follow-ups'
    | '/inquiries'
    | '/inventory'
    | '/invoices'
    | '/lab-reports'
    | '/messages'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/users'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/follow-ups'
    | '/inquiries'
    | '/inventory'
    | '/invoices'
    | '/lab-reports'
    | '/messages'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/users'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/follow-ups'
    | '/inquiries'
    | '/inventory'
    | '/invoices'
    | '/lab-reports'
    | '/messages'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/users'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  FollowUpsRoute: typeof FollowUpsRoute
  InquiriesRoute: typeof InquiriesRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LabReportsRoute: typeof LabReportsRoute
  MessagesRoute: typeof MessagesRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PrescriptionsRoute: typeof PrescriptionsRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-reports': {
      id: '/lab-reports'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof LabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DoctorsRoute: DoctorsRoute,
  FollowUpsRoute: FollowUpsRoute,
  InquiriesRoute: InquiriesRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LabReportsRoute: LabReportsRoute,
  MessagesRoute: MessagesRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PrescriptionsRoute: PrescriptionsRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
